spring:
  application:
    name: user-service

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
