spring:
  application:
    name: user-service
  profiles:
    active: dev

server:
  port: 9001


eureka:
  instance:
    hostname: reg.jeffgao.com.cn
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8085/eureka/

