
server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://106.14.202.160:3306/docker_database?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(0xb9b8sMHIW++yxeeqbJ9A==)
    password: ENC(I943uG5/6fSobkasAMTJZg==)
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
      max-lifetime: 1800000
      auto-commit: true
      connection-test-query: SELECT 1

mapper:
  identity: MYSQL   # 取主键的方式
  before: true      # 主键递增
  not-empty: true   # 按主键插入或更新时，是否判断字符串 != ''
  style: camelhumpandlowercase  # 实体类与表中字段的映射方式：驼峰转带下划线的小写格式
  wrap-keyword: '{0}'   # 自动配置关键字，配置后不需要使用 @Column 指定别名
  safe-delete: true   # 删除时必须设置查询条件
  safe-update: true   # 更新时必须设置查询条件
  use-java-type: true   # 是否映射Java基本数据类型
  mappers: tk.mybatis.mapper.common.Mapper

  ### 加密工具 ####
jasypt:
  encryptor:
    password: w9ewfsd395afkzxc43534nul3v90ochf3

